---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

env:
  matrix:
    - EMBER_CHANNEL=release
    - EMBER_CHANNEL=beta
    - EMBER_CHANNEL=canary
