---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ./node_modules/.bin/ember try:each

deploy:
  - provider: script
    skip_cleanup: true
    script: node_modules/.bin/ember deploy production --verbose
    on:
      branch: master
env:
  global:
    secure: hVBPd3JlL3rWo+ajwTTGnNNltEOhfaITrY9P0hBYsFrSOqt4hcIkr5X3mXmoKbN+TuEbDh9wtuVVe+twR+dLPErFZRuNdlYyZsGIJxucL7tvEG+iLda77yvCiwrwOdYWwJEqqsvsMiizlwDyd8Xk+htLMiHJTKrEx1IJ9pb3C7s=
